server:
  port: ${PORT:3000}

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/billing_and_stock_management}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  client:
    url: ${CLIENT_URL:http://localhost:4200/}

jwt:
  secret: ${JWT_SECRET:dev-secret}
  refreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS:1800000}