server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none                       # Turn off auto DDL
      properties:
        hibernate.jdbc.lob.non_contextual_creation: true  # Reduce Hibernate overhead
        hibernate.generate_statistics: false             # Disable extra stats
        hibernate.temp.use_jdbc_metadata_defaults: false # Reduce metadata checks
    show-sql: false

  main:
    allow-bean-definition-overriding: true # Sometimes helps with slow startup

app:
  client:
    url: ${CLIENT_URL}

jwt:
  secret: ${JWT_SECRET}
  refreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS:1800000}

tebi:
  endpoint: https://s3.tebi.io
  bucket: ${TEBI_BUCKET_NAME}
  access-key: ${TEBI_ACCESS_KEY}
  secret-key: ${TEBI_SECRET_KEY}
  region: us-east-1

branding:
  default-logo-url: https://s3.tebi.io/${TEBI_BUCKET_NAME}/logos/default-gst-medicose.png
